### ISSUE TITLE
Remove banner

### ISSUE THREAD

**Issue by lguerard** [Gulzt/commentBanner#3]
Hi,

I tried updating a banner that I made previously but it messed up everything so I looked at how to remove the banner and couldn't find it.

Is there a shortcut to do so ? 

Thanks.

**Comment by paulvanvulpen** [comment]
Good question!

The banner tool creates raw text, by design there is no way to explicitly remove the banner away to get the original text back. You could however create a regular expression that would do just that.

In practice I haven't seen the need personally. If I want to change one line in a multi-line banner, I create a fresh banner just for one line, remove the top and bottom line and replace the line to be changed with the remainder.

I will consider this feature in a future update.

**Comment by lguerard** [comment]
Thanks for the fast answer ! :).

Didn't actually thought about merging two banners but that would indeed do the work I guess.
